backend:
  name: github
  repo: StudioOM/testsite
  branch: main
# Add these two lines to stop it from going to Netlify
  base_url: https://api.github.com
  auth_type: implicit
  
media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string"}
          - {label: "Vision Text", name: "vision_text", widget: "markdown"}
