backend:
  name: github
  repo: StudioOM/testsite
  branch: main
  auth_type: implicit
  client_id: Ov23liX8UuMKwIfnlQse

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string"}
          - {label: "Vision Text", name: "vision_text", widget: "markdown"}
